Server: add missing include to nf_callback.c
```
nf_callbacks.c:130:13: error: implicit declaration of function 'kill' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            kill((pid_t)pid, SIGTERM);
```